In [1]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 


train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [2]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [3]:
model = nn.Linear(2, 2, bias=True)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [4]:
for epoch in range(20000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.6720, 0.0879],
        [0.7226, 0.4578]], requires_grad=True), Parameter containing:
tensor([-0.2985,  0.2456], requires_grad=True)], Cost : 0.058
Epoch : 2000, Model : [Parameter containing:
tensor([[0.8143, 0.0145],
        [0.8441, 0.3951]], requires_grad=True), Parameter containing:
tensor([-0.5142,  0.0614], requires_grad=True)], Cost : 0.015
Epoch : 3000, Model : [Parameter containing:
tensor([[ 0.8866, -0.0230],
        [ 0.9059,  0.3631]], requires_grad=True), Parameter containing:
tensor([-0.6240, -0.0325], requires_grad=True)], Cost : 0.004
Epoch : 4000, Model : [Parameter containing:
tensor([[ 0.9235, -0.0421],
        [ 0.9374,  0.3468]], requires_grad=True), Parameter containing:
tensor([-0.6800, -0.0802], requires_grad=True)], Cost : 0.001
Epoch : 5000, Model : [Parameter containing:
tensor([[ 0.9423, -0.0518],
        [ 0.9534,  0.3385]], requires_grad=True), Parameter containing:
tensor([-0.7085, -0.1046], requires