In [3]:
import torch


cpu = torch.FloatTensor([1, 2, 3])
gpu = cpu.cuda()
gpu2cpu = gpu.cpu()
cpu2gpu = cpu.to("cuda")
print(cpu)
print(gpu)
print(gpu2cpu)
print(cpu2gpu)

tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')


In [1]:
# 애플 실리콘이 탑재된 맥 사용자의 경우
import torch


cpu = torch.FloatTensor([1, 2, 3])
gpu = cpu.to("mps")
gpu2cpu = gpu.cpu()
print(cpu)
print(gpu)
print(gpu2cpu)

RuntimeError: PyTorch is not linked with support for mps devices