In [1]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 


train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [2]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [3]:
model = nn.Linear(2, 2, bias=False)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [4]:
for epoch in range(20000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[ 0.7427, -0.0259],
        [ 0.3380,  0.8162]], requires_grad=True)], Cost : 0.095
Epoch : 2000, Model : [Parameter containing:
tensor([[ 0.9393, -0.1847],
        [ 0.4945,  0.6898]], requires_grad=True)], Cost : 0.060
Epoch : 3000, Model : [Parameter containing:
tensor([[ 1.0954, -0.3110],
        [ 0.6188,  0.5892]], requires_grad=True)], Cost : 0.038
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.2195, -0.4114],
        [ 0.7175,  0.5093]], requires_grad=True)], Cost : 0.024
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.3181, -0.4912],
        [ 0.7960,  0.4458]], requires_grad=True)], Cost : 0.015
Epoch : 6000, Model : [Parameter containing:
tensor([[ 1.3965, -0.5546],
        [ 0.8584,  0.3954]], requires_grad=True)], Cost : 0.010
Epoch : 7000, Model : [Parameter containing:
tensor([[ 1.4588, -0.6049],
        [ 0.9080,  0.3553]], requires_grad=True)], Cost : 0.006
Epoch : 8000, Model : [Parameter containi